universe = container
container_image = docker://lavansurendra/wiscohumanoids:v4
docker_pull_policy=always

log = CHTC_logs/$(Cluster).$(Process).log
error = CHTC_errors/$(Cluster).$(Process).err
output = CHTC_output/$(Cluster).$(Process).out

# Requesting 10 CPUs to handle the 4 parallel MuJoCo environments
request_cpus = 32
request_memory = 32GB
request_disk = 20GB

executable = train.sh
arguments = --env_id G1Env --num_envs 30 --timesteps_per_env 10000 --xml_path /workspace/environment/g1_scene.xml --save_freq 100000


# Retrieve training output and local W&B data upon exit
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_output_files = output/

queue 1
