container_image = docker://djb119/locomotion:latest
universe = container

log = $(Cluster).$(Process).log
error = $(Cluster).$(Process).err
output = $(Cluster).$(Process).out

request_cpus = 8
request_memory = 32GB
request_disk = 60GB

executable = train.sh
arguments = $(Process)
transfer_input_files = environment/, train.py

# Tell CHTC to bring the 'output' folder back when finished
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_output_files = output/

queue 1