universe = container
container_image = docker://lavansurendra/wiscohumanoids:v2
+EverythingExtra = "docker_pull_policy=always"

log = CHTC_logs/$(Cluster).$(Process).log
error = CHTC_errors/$(Cluster).$(Process).err
output = CHTC_output/$(Cluster).$(Process).out

# Requesting 10 CPUs to handle the 4 parallel MuJoCo environments
request_cpus = 16
request_memory = 16GB
request_disk = 20GB

executable = train.sh
arguments = --env-id G1Env --num_envs 16 --timesteps_per_env 10000 --xml_path /workspace/environment/g1_scene.xml --save_freq 10000


# Retrieve training output and local W&B data upon exit
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_output_files = output/

queue 1
